Vagrant.configure(2) do |config|
  config.vm.provider "virtualbox" do |v|
    v.gui=false
  end

  config.vm.define "workbench" do |device|
      device.vm.provider "virtualbox" do |v|
        v.name = "workbench"
        v.memory = 1024
      end
      device.vm.hostname = "workbench"
      device.vm.box = "boxcutter/ubuntu1404"


    device.vm.network "private_network", virtualbox__intnet: "net_mgmt", auto_config: false


      device.vm.synced_folder ".", "/vagrant", disabled: true
      device.vm.provision :shell , inline: "sudo sed -i 's/sleep [0-9]*/sleep 1/' /etc/init/failsafe.conf"
      device.vm.provision :shell , path: "./helper_scripts/workbench.sh"
      device.vm.provision "file", source: "./helper_scripts/rename_eth_swp", destination: "/home/vagrant/rename_eth_swp"
      device.vm.provision "file", source: "./helper_scripts/autogenerated/workbench_remap_eth", destination: "/home/vagrant/remap_eth"
      device.vm.provision :shell , inline: "mv /home/vagrant/rename_eth_swp /etc/init.d/rename_eth_swp"
      device.vm.provision :shell , inline: "mv /home/vagrant/remap_eth /etc/default/remap_eth"
      device.vm.provision :shell , inline: "chmod 755 /etc/init.d/rename_eth_swp"
      device.vm.provision :shell , inline: "sudo sed -i '/exit 0/d' /etc/rc.local "
      device.vm.provision :shell , inline: "sudo echo '/etc/init.d/rename_eth_swp start' >> /etc/rc.local "
      device.vm.provision :shell , inline: "sudo echo 'exit 0' >> /etc/rc.local "
      device.vm.provision :shell , inline: "/etc/init.d/rename_eth_swp verbose"

      device.vm.provider "virtualbox" do |vbox|

        vbox.customize ['modifyvm', :id, '--nicpromisc2', 'allow-vms']


        vbox.customize ["modifyvm", :id, "--nictype1", "virtio"]

        vbox.customize ["modifyvm", :id, "--nictype2", "virtio"]

      end

      device.vm.provision "ansible" do |ansible|
        ansible.playbook = "./wbench/wbench.yml"

      end
    end





  config.vm.define "spine01" do |device|
      device.vm.provider "virtualbox" do |v|
        v.name = "spine01"
        v.memory = 1256
      end

      device.vm.box = "vsr"
      device.ssh.private_key_path = "./id_rsa"
      device.ssh.shell = "sh"
      device.vm.synced_folder ".", "/vagrant", disabled: true
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_mgmt", auto_config: false , :mac => "A00000000021"
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s1l1", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s1l2", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s1l3", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s1l4", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s1l5", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s1l6", auto_config: false
    end


  config.vm.define "spine02" do |device|
      device.vm.provider "virtualbox" do |v|
        v.name = "spine02"
        v.memory = 1256
      end

      device.vm.box = "vsr"
      device.ssh.private_key_path = "./id_rsa"
      device.ssh.shell = "sh"
      device.vm.synced_folder ".", "/vagrant", disabled: true
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_mgmt", auto_config: false , :mac => "A00000000022"
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s2l1", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s2l2", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s2l3", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s2l4", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s2l5", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s2l6", auto_config: false
    end


  config.vm.define "spine03" do |device|
      device.vm.provider "virtualbox" do |v|
        v.name = "spine03"
        v.memory = 1256
      end

      device.vm.box = "vsr"
      device.ssh.private_key_path = "./id_rsa"
      device.ssh.shell = "sh"
      device.vm.synced_folder ".", "/vagrant", disabled: true
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_mgmt", auto_config: false , :mac => "A00000000023"
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s3l1", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s3l2", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s3l3", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s3l4", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s3l5", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s3l6", auto_config: false
    end


  config.vm.define "spine04" do |device|
      device.vm.provider "virtualbox" do |v|
        v.name = "spine04"
        v.memory = 1256
      end

      device.vm.box = "vsr"
      device.ssh.private_key_path = "./id_rsa"
      device.ssh.shell = "sh"
      device.vm.synced_folder ".", "/vagrant", disabled: true
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_mgmt", auto_config: false , :mac => "A00000000024"
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s4l1", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s4l2", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s4l3", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s4l4", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s4l5", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s4l6", auto_config: false
    end



  config.vm.define "leaf01" do |device|
      device.vm.provider "virtualbox" do |v|
        v.name = "leaf01"
        v.memory = 1256
      end

      device.vm.box = "vsr"
      device.ssh.private_key_path = "./id_rsa"
      device.ssh.shell = "sh"
      device.vm.synced_folder ".", "/vagrant", disabled: true
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_mgmt", auto_config: false , :mac => "A00000000011"
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s1l1", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s2l1", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s3l1", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s4l1", auto_config: false
    end



  config.vm.define "leaf02" do |device|
      device.vm.provider "virtualbox" do |v|
        v.name = "leaf02"
        v.memory = 1256
      end

      device.vm.box = "vsr"
      device.ssh.private_key_path = "./id_rsa"
      device.ssh.shell = "sh"
      device.vm.synced_folder ".", "/vagrant", disabled: true
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_mgmt", auto_config: false , :mac => "A00000000012"
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s1l2", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s2l2", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s3l2", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s4l2", auto_config: false
    end



  config.vm.define "leaf03" do |device|
      device.vm.provider "virtualbox" do |v|
        v.name = "leaf03"
        v.memory = 1256
      end

      device.vm.box = "vsr"
      device.ssh.private_key_path = "./id_rsa"
      device.ssh.shell = "sh"
      device.vm.synced_folder ".", "/vagrant", disabled: true
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_mgmt", auto_config: false , :mac => "A00000000013"
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s1l3", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s2l3", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s3l3", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s4l3", auto_config: false
    end



  config.vm.define "leaf04" do |device|
      device.vm.provider "virtualbox" do |v|
        v.name = "leaf04"
        v.memory = 1256
      end

      device.vm.box = "vsr"
      device.ssh.private_key_path = "./id_rsa"
      device.ssh.shell = "sh"
      device.vm.synced_folder ".", "/vagrant", disabled: true
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_mgmt", auto_config: false , :mac => "A00000000014"
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s1l4", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s2l4", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s3l4", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s4l4", auto_config: false
    end



  config.vm.define "leaf05" do |device|
      device.vm.provider "virtualbox" do |v|
        v.name = "leaf05"
        v.memory = 1256
      end

      device.vm.box = "vsr"
      device.ssh.private_key_path = "./id_rsa"
      device.ssh.shell = "sh"
      device.vm.synced_folder ".", "/vagrant", disabled: true
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_mgmt", auto_config: false , :mac => "A00000000015"
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s1l5", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s2l5", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s3l5", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s4l5", auto_config: false
    end



  config.vm.define "leaf06" do |device|
      device.vm.provider "virtualbox" do |v|
        v.name = "leaf06"
        v.memory = 1256
      end

      device.vm.box = "vsr"
      device.ssh.private_key_path = "./id_rsa"
      device.ssh.shell = "sh"
      device.vm.synced_folder ".", "/vagrant", disabled: true
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_mgmt", auto_config: false , :mac => "A00000000016"
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s1l6", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s2l6", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s3l6", auto_config: false
      device.vm.network "private_network", nic_type: "82540EM", virtualbox__intnet: "net_s4l6", auto_config: false
    end
  end
